import pathlib
import sys
import subprocess


FIXTURE = pathlib.Path(__file__).parent / "fixtures" / "golden_blueprint.yaml"
SCRIPT = pathlib.Path(__file__).resolve().parent.parent / "scripts" / "ddl_compile.py"


def _run(args, cwd):
    return subprocess.run([sys.executable, str(SCRIPT), *args], cwd=cwd, capture_output=True, text=True)


def test_golden_postgres(tmp_path):
    r = _run([str(FIXTURE), "--out", str(tmp_path), "--dialect", "postgres"], cwd=tmp_path)
    assert r.returncode == 0, r.stderr
    for f in [
        "migrations/V001__create_schema.sql",
        "migrations/V002__create_tables.sql",
        "migrations/V003__create_indexes.sql",
        "migrations/V004__create_constraints.sql",
        "seed/01_customer_sample.sql",
        "seed/01_address_sample.sql",
        "src/main/java/com/example/crm/Customer.java",
        "src/main/java/com/example/crm/Address.java",
        "ddl-report.md",
    ]:
        assert (tmp_path / f).exists(), f"missing {f}"
    v004 = (tmp_path / "migrations" / "V004__create_constraints.sql").read_text()
    assert "fk_address__customer_id" in v004
    assert "chk_customer_email" in v004


def test_golden_hsqldb(tmp_path):
    r = _run([str(FIXTURE), "--out", str(tmp_path), "--dialect", "hsqldb"], cwd=tmp_path)
    assert r.returncode == 0, r.stderr
    v002 = (tmp_path / "migrations" / "V002__create_tables.sql").read_text()
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY" in v002
