import pathlib
import subprocess
import sys
import textwrap


def write_blueprint(tmp_path, passed=True):
    wiki = tmp_path / "wiki"
    wiki.mkdir()
    (wiki / "_blueprint.yaml").write_text(textwrap.dedent(f"""
        version: 1
        project: 테스트
        entities:
          - name: customer
            table: customer
            schema: crm
            domain: [고객관리]
            preset: 고객관리
            columns:
              - {{name: id, type: bigserial, pk: true, null: false}}
              - {{name: email, type: 'varchar(255)', null: false}}
            indexes:
              - {{name: ix_email, columns: [email], unique: true}}
        relations: []
        business_rules: []
        validation:
          passed: {str(passed).lower()}
        """).strip(), encoding="utf-8")
    return wiki


def run(args, cwd):
    script = pathlib.Path(__file__).resolve().parent.parent / "scripts" / "ddl_compile.py"
    return subprocess.run([sys.executable, str(script), *args], cwd=cwd, capture_output=True, text=True)


def test_compile_success(tmp_path):
    wiki = write_blueprint(tmp_path)
    out = tmp_path / "out"
    r = run([str(wiki / "_blueprint.yaml"), "--out", str(out), "--package", "com.example.crm"], cwd=tmp_path)
    assert r.returncode == 0, r.stderr
    assert (out / "migrations" / "V001__create_schema.sql").exists()
    assert (out / "migrations" / "V002__create_tables.sql").exists()
    assert (out / "migrations" / "V003__create_indexes.sql").exists()
    assert (out / "migrations" / "V004__create_constraints.sql").exists()
    assert (out / "seed" / "01_customer_sample.sql").exists()
    assert (out / "src" / "main" / "java" / "com" / "example" / "crm" / "Customer.java").exists()
    assert (out / "ddl-report.md").exists()


def test_compile_aborts_on_failed_validation(tmp_path):
    wiki = write_blueprint(tmp_path, passed=False)
    out = tmp_path / "out"
    r = run([str(wiki / "_blueprint.yaml"), "--out", str(out)], cwd=tmp_path)
    assert r.returncode == 1
    assert "Stage 1 validation failed" in r.stderr


def test_compile_hsqldb_dialect(tmp_path):
    wiki = write_blueprint(tmp_path)
    out = tmp_path / "out"
    r = run([str(wiki / "_blueprint.yaml"), "--out", str(out), "--dialect", "hsqldb"], cwd=tmp_path)
    assert r.returncode == 0, r.stderr
    v002 = (out / "migrations" / "V002__create_tables.sql").read_text(encoding="utf-8")
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY" in v002
