import pathlib
from ddl_gen import generate_ddl


def make_blueprint():
    return {
        "version": 1,
        "entities": [{
            "name": "customer", "table": "customer", "schema": "crm",
            "columns": [
                {"name": "id", "type": "bigserial", "pk": True, "null": False},
                {"name": "email", "type": "varchar(255)", "null": False},
            ],
            "indexes": [{"name": "ix_email", "columns": ["email"], "unique": True}],
        }],
        "relations": [],
        "business_rules": [],
    }


def test_hsqldb_uses_identity(tmp_path):
    generate_ddl(make_blueprint(), tmp_path, dialect="hsqldb")
    v002 = (tmp_path / "migrations" / "V002__create_tables.sql").read_text(encoding="utf-8")
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY" in v002
    assert "BIGSERIAL" not in v002


def test_hsqldb_creates_schema_natively(tmp_path):
    generate_ddl(make_blueprint(), tmp_path, dialect="hsqldb")
    v001 = (tmp_path / "migrations" / "V001__create_schema.sql").read_text(encoding="utf-8")
    assert "CREATE SCHEMA IF NOT EXISTS crm" in v001
