import pytest
from dialect import get_dialect, DialectError


def test_get_postgres():
    d = get_dialect("postgres")
    assert d.name == "postgres"
    assert d.schema_strategy == "native"
    assert d.type_map["bigserial"] == "BIGSERIAL"
    assert d.idempotent_insert == "ON CONFLICT DO NOTHING"
    assert d.regex_op == "~"


def test_get_hsqldb():
    d = get_dialect("hsqldb")
    assert d.name == "hsqldb"
    assert d.schema_strategy == "native"
    assert d.type_map["bigserial"] == "BIGINT GENERATED BY DEFAULT AS IDENTITY"
    assert d.idempotent_insert == "MERGE"
    assert d.regex_op is None


def test_unknown_dialect():
    with pytest.raises(DialectError, match="unknown"):
        get_dialect("oracle")


def test_template_dir_postgres():
    d = get_dialect("postgres")
    assert d.template_dir == "postgres"


def test_template_dir_hsqldb():
    d = get_dialect("hsqldb")
    assert d.template_dir == "hsqldb"
