from dataclasses import dataclass, field
from typing import Dict, Optional


class DialectError(Exception):
    pass


@dataclass
class Dialect:
    name: str
    template_dir: str
    schema_strategy: str           # "native" | "prefix"
    type_map: Dict[str, str]
    idempotent_insert: str         # "ON CONFLICT DO NOTHING" | "INSERT IGNORE" | "MERGE"
    regex_op: Optional[str]        # infix regex operator or None


POSTGRES = Dialect(
    name="postgres",
    template_dir="postgres",
    schema_strategy="native",
    type_map={
        "bigserial": "BIGSERIAL",
        "bigint": "BIGINT",
        "integer": "INTEGER",
        "varchar": "VARCHAR",
        "text": "TEXT",
        "boolean": "BOOLEAN",
        "timestamp": "TIMESTAMP",
        "date": "DATE",
        "numeric": "NUMERIC",
    },
    idempotent_insert="ON CONFLICT DO NOTHING",
    regex_op="~",
)

HSQLDB = Dialect(
    name="hsqldb",
    template_dir="hsqldb",
    schema_strategy="native",
    # HSQLDB IDENTITY trap (Growth-27, 2026-05-21):
    # GENERATED BY DEFAULT AS IDENTITY starts at 0, not 1 like PostgreSQL BIGSERIAL.
    # Smoke-tests and seed SQL that hardcode FK values like `fiscal_period_id, 1`
    # will FK-violate against the first auto-assigned row (id=0).
    # Always use Statement.RETURN_GENERATED_KEYS + ResultSet to capture the actual id.
    # See: business-fullstack-creater/.tmp_e2e_finance/FinanceSmoke.java (reference harness)
    type_map={
        "bigserial": "BIGINT GENERATED BY DEFAULT AS IDENTITY",
        "bigint": "BIGINT",
        "integer": "INTEGER",
        "varchar": "VARCHAR",
        "text": "LONGVARCHAR",
        "boolean": "BOOLEAN",
        "timestamp": "TIMESTAMP",
        "date": "DATE",
        "numeric": "NUMERIC",
    },
    idempotent_insert="MERGE",
    regex_op=None,
)

MYSQL = Dialect(
    name="mysql",
    template_dir="mysql",
    schema_strategy="native",
    type_map={
        "bigserial": "BIGINT AUTO_INCREMENT",
        "bigint": "BIGINT",
        "integer": "INT",
        "varchar": "VARCHAR",
        "text": "TEXT",
        "boolean": "TINYINT(1)",
        "timestamp": "DATETIME",
        "date": "DATE",
        "numeric": "DECIMAL",
    },
    idempotent_insert="INSERT IGNORE",
    regex_op="REGEXP",
)

_REGISTRY = {"postgres": POSTGRES, "hsqldb": HSQLDB, "mysql": MYSQL}


def get_dialect(name: str) -> Dialect:
    if name not in _REGISTRY:
        raise DialectError(f"unknown dialect: {name}")
    return _REGISTRY[name]
