from dataclasses import dataclass, field
from typing import Dict, Optional


class DialectError(Exception):
    pass


@dataclass
class Dialect:
    name: str
    template_dir: str
    schema_strategy: str           # "native" | "prefix"
    type_map: Dict[str, str]
    idempotent_insert: str         # "ON CONFLICT DO NOTHING" | "INSERT IGNORE" | "MERGE"
    regex_op: Optional[str]        # infix regex operator or None


POSTGRES = Dialect(
    name="postgres",
    template_dir="postgres",
    schema_strategy="native",
    type_map={
        "bigserial": "BIGSERIAL",
        "bigint": "BIGINT",
        "integer": "INTEGER",
        "varchar": "VARCHAR",
        "text": "TEXT",
        "boolean": "BOOLEAN",
        "timestamp": "TIMESTAMP",
        "date": "DATE",
        "numeric": "NUMERIC",
    },
    idempotent_insert="ON CONFLICT DO NOTHING",
    regex_op="~",
)

HSQLDB = Dialect(
    name="hsqldb",
    template_dir="hsqldb",
    schema_strategy="native",
    type_map={
        "bigserial": "BIGINT GENERATED BY DEFAULT AS IDENTITY",
        "bigint": "BIGINT",
        "integer": "INTEGER",
        "varchar": "VARCHAR",
        "text": "LONGVARCHAR",
        "boolean": "BOOLEAN",
        "timestamp": "TIMESTAMP",
        "date": "DATE",
        "numeric": "NUMERIC",
    },
    idempotent_insert="MERGE",
    regex_op=None,
)

_REGISTRY = {"postgres": POSTGRES, "hsqldb": HSQLDB}


def get_dialect(name: str) -> Dialect:
    if name not in _REGISTRY:
        raise DialectError(f"unknown dialect: {name}")
    return _REGISTRY[name]
